LEXICON_LANGUAGE_RU: dict[str, str] = {
    'ru': '🇷🇺 russian',
    'en': '🇬🇧󠁧󠁢󠁥󠁮󠁧󠁿 english',
    'de': '🇩🇪 german',
    'fr': '🇫🇷 french',
    'it': '🇮🇹 italian',
    'es': '🇮🇸 spanish',
    'be': '🇧🇾 belarusian',
    'uk': '🇺🇦 ukrainian',
    'sq': 'albanian',
    'ar': 'arabic',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'zh-CN': 'chinese_simplified',
    'zh-TW': 'chinese_traditional',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'gl': 'galician',
    'el': 'greek',
    'iw': 'hebrew',
    'hi': 'hindi',
    'hu': 'hungarian',
    'is': 'icelandic',
    'id': 'indonesian',
    'ga': 'irish',
    'ja': 'japanese',
    'ko': 'korean',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'mk': 'macedonian',
    'ms': 'malay',
    'mt': 'maltese',
    'no': 'norwegian',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'ro': 'romanian',
    'sr': 'serbian',
    'sk': 'slovak',
    'sl': 'slovenian',
    'sw': 'swahili',
    'sv': 'swedish',
    'th': 'thai',
    'tr': 'turkish',
    'vi': 'vietnamese',
    'cy': 'welsh',
}

LEXICON_LANGUAGE_SMALL_RU: dict[str, str] = {
    'ru': '🇷🇺 russian',
    'en': '🇬🇧󠁧󠁢󠁥󠁮󠁧󠁿 english',
    'de': '🇩🇪 german',
    'fr': '🇫🇷 french',
    'it': '🇮🇹 italian',
    'es': '🇮🇸 spanish',
    'be': '🇧🇾 belarusian',
    'uk': '🇺🇦 ukrainian',
}
